package huuduc;

import javax.swing.text.Element;
import javax.swing.text.PasswordView;

/**
 *
 * @author huuducngo
 */
public class frm_miniTOTP extends javax.swing.JFrame {

    /**
     * Creates new form frm_testTOTP
     */
    public frm_miniTOTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lb_qrcode = new javax.swing.JLabel();
        txt_checktoken = new javax.swing.JTextField();
        lb_checkOTP = new javax.swing.JLabel();
        lb_tokenStatus = new javax.swing.JLabel();
        txt_otpToken = new javax.swing.JTextField();
        btn_checktoken = new javax.swing.JButton();
        lb_OTPtoken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_accountpool = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_otpauth = new javax.swing.JTextArea();
        lb_otpauth = new javax.swing.JLabel();
        lb_timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("miniTOTP");
        setMaximumSize(new java.awt.Dimension(800, 470));
        setName("miniTOTP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 470));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        lb_title.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("miniTOTP");
        lb_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lb_username.setText("Username:");

        lb_password.setText("Password:");

        btn_login.setText("Login");

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        lb_qrcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_qrcode.setText("QRCode Is HERE!!!");
        lb_qrcode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_qrcode.setPreferredSize(new java.awt.Dimension(200, 200));

        lb_checkOTP.setText("Check Token TOTP");

        lb_tokenStatus.setText("Token Status");

        txt_otpToken.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        txt_otpToken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_otpToken.setText("888888");
        txt_otpToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otpTokenActionPerformed(evt);
            }
        });

        btn_checktoken.setText("Check");

        lb_OTPtoken.setText("OTP Token");

        tb_accountpool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Secret Key"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_accountpool);
        if (tb_accountpool.getColumnModel().getColumnCount() > 0) {
            tb_accountpool.getColumnModel().getColumn(0).setMinWidth(200);
            tb_accountpool.getColumnModel().getColumn(0).setPreferredWidth(200);
            tb_accountpool.getColumnModel().getColumn(0).setMaxWidth(500);
            tb_accountpool.getColumnModel().getColumn(1).setMinWidth(200);
            tb_accountpool.getColumnModel().getColumn(1).setPreferredWidth(200);
            tb_accountpool.getColumnModel().getColumn(1).setMaxWidth(500);
        }

        txt_otpauth.setColumns(20);
        txt_otpauth.setRows(5);
        jScrollPane2.setViewportView(txt_otpauth);

        lb_otpauth.setText("OTPAuth");

        lb_timer.setText("TImer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_title)
                            .addComponent(lb_username)
                            .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_password)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_register)
                                .addGap(50, 50, 50)
                                .addComponent(btn_login))
                            .addComponent(lb_checkOTP)
                            .addComponent(txt_checktoken, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_checktoken)
                                .addGap(6, 6, 6)
                                .addComponent(lb_tokenStatus)))
                        .addGap(30, 30, 30)
                        .addComponent(lb_qrcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_otpToken, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_otpauth)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_timer)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_OTPtoken))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_title)
                        .addGap(6, 6, 6)
                        .addComponent(lb_username)
                        .addGap(6, 6, 6)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lb_password)
                        .addGap(6, 6, 6)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_register)
                            .addComponent(btn_login))
                        .addGap(18, 18, 18)
                        .addComponent(lb_checkOTP)
                        .addGap(6, 6, 6)
                        .addComponent(txt_checktoken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_checktoken)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lb_tokenStatus))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_OTPtoken)
                                    .addComponent(lb_timer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_otpToken, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_otpauth)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lb_qrcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int row = 0, col = 0;
    
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        String name = txt_username.getText();
        String pass = new String(txt_password.getPassword());
        tb_accountpool.setValueAt(name, row, col);
        tb_accountpool.setValueAt(pass, row, col + 1);
        row++;
        col = 0;
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_otpTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otpTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otpTokenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_miniTOTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checktoken;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_OTPtoken;
    private javax.swing.JLabel lb_checkOTP;
    private javax.swing.JLabel lb_otpauth;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_qrcode;
    private javax.swing.JLabel lb_timer;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_tokenStatus;
    private javax.swing.JLabel lb_username;
    private javax.swing.JTable tb_accountpool;
    private javax.swing.JTextField txt_checktoken;
    private javax.swing.JTextField txt_otpToken;
    private javax.swing.JTextArea txt_otpauth;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
