package huuduc;

import java.awt.event.ActionEvent;
import javax.swing.Timer;
import javax.swing.text.Element;
import javax.swing.text.PasswordView;

/**
 *
 * @author huuducngo
 */
public class frm_miniTOTP extends javax.swing.JFrame {
    
    Timer t, timeStamp;
    
    public frm_miniTOTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lb_qrcode = new javax.swing.JLabel();
        txt_checktoken = new javax.swing.JTextField();
        lb_checkOTP = new javax.swing.JLabel();
        lb_tokenStatus = new javax.swing.JLabel();
        txt_otpToken = new javax.swing.JTextField();
        btn_checktoken = new javax.swing.JButton();
        lb_OTPtoken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_accountpool = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_otpauth = new javax.swing.JTextArea();
        lb_otpauth = new javax.swing.JLabel();
        lb_timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("miniTOTP");
        setMaximumSize(new java.awt.Dimension(550, 550));
        setMinimumSize(new java.awt.Dimension(550, 550));
        setName("miniTOTP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_title.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("miniTOTP");
        lb_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, -1, -1));

        lb_username.setText("Username:");
        getContentPane().add(lb_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 61, -1, -1));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 83, 200, -1));

        lb_password.setText("Password:");
        getContentPane().add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, -1, -1));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 133, 200, -1));

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 161, -1, -1));

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 161, -1, -1));

        lb_qrcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_qrcode.setText("QRCode Is HERE!!!");
        lb_qrcode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_qrcode.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(lb_qrcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));
        getContentPane().add(txt_checktoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 208, 124, -1));

        lb_checkOTP.setText("Check Token TOTP");
        getContentPane().add(lb_checkOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lb_tokenStatus.setText("Token Status");
        getContentPane().add(lb_tokenStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 190, -1, -1));

        txt_otpToken.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        txt_otpToken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_otpToken.setText("888888");
        txt_otpToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otpTokenActionPerformed(evt);
            }
        });
        getContentPane().add(txt_otpToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 271, -1, 78));

        btn_checktoken.setText("Check");
        getContentPane().add(btn_checktoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 208, -1, -1));

        lb_OTPtoken.setText("OTP Token");
        getContentPane().add(lb_OTPtoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        tb_accountpool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Password", "Secret Key"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_accountpool);
        if (tb_accountpool.getColumnModel().getColumnCount() > 0) {
            tb_accountpool.getColumnModel().getColumn(0).setMinWidth(100);
            tb_accountpool.getColumnModel().getColumn(0).setPreferredWidth(100);
            tb_accountpool.getColumnModel().getColumn(0).setMaxWidth(200);
            tb_accountpool.getColumnModel().getColumn(1).setMinWidth(100);
            tb_accountpool.getColumnModel().getColumn(1).setPreferredWidth(100);
            tb_accountpool.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 505, 120));

        txt_otpauth.setColumns(20);
        txt_otpauth.setRows(5);
        jScrollPane2.setViewportView(txt_otpauth);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 271, 300, 78));

        lb_otpauth.setText("OTPAuth");
        getContentPane().add(lb_otpauth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lb_timer.setText("TImer");
        getContentPane().add(lb_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int row = 0, col = 0;
    
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        String name = txt_username.getText();
        String pass = new String(txt_password.getPassword());
        tb_accountpool.setValueAt(name, row, col);
        tb_accountpool.setValueAt(pass, row, col + 1);
        row++;
        col = 0;
    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_otpTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otpTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otpTokenActionPerformed
    
    private String updatetimestamp() {
        return String.valueOf(System.currentTimeMillis() / 1000L);
    }
    
    boolean status = false;
   
    private String getTime() {
        long k = 30 - (System.currentTimeMillis() / 1000L % 30);
        return String.valueOf(k);
    }
    
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
         status = status == false; // máy tự viết lại hàm if này, thấy nó lạ quá :V 
        
        switch (status) {
            case true -> {
                lb_timer.setText(getTime());
                //lb_timeStamp.setText(updatetimestamp());
                t =  new Timer(1000, (ActionEvent e) -> {
                    lb_timer.setText(getTime());
                    //lb_timeStamp.setText(updatetimestamp());
                });
                t.start();
            }
            case false -> {
//                lb_timer.setText("Press START!");
//                btn_start.setText("Start");
//                lb_timeStamp.setText(updatetimestamp());
//                timeStamp = new Timer(1000, (ActionEvent updatTimeStamp) -> {
//                   lb_timeStamp.setText(updatetimestamp()); 
//                });
//                timeStamp.start();
                t.stop();
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_miniTOTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_miniTOTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checktoken;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb_OTPtoken;
    private javax.swing.JLabel lb_checkOTP;
    private javax.swing.JLabel lb_otpauth;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_qrcode;
    private javax.swing.JLabel lb_timer;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_tokenStatus;
    private javax.swing.JLabel lb_username;
    private javax.swing.JTable tb_accountpool;
    private javax.swing.JTextField txt_checktoken;
    private javax.swing.JTextField txt_otpToken;
    private javax.swing.JTextArea txt_otpauth;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
