package totp;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import lib_totp.code.CodeGenerator;
import lib_totp.code.CodeVerifier;
import lib_totp.code.DefaultCodeGenerator;
import lib_totp.code.DefaultCodeVerifier;
import lib_totp.code.HashingAlgorithm;
import lib_totp.exceptions.QrGenerationException;
import lib_totp.qr.QrData;
import lib_totp.qr.QrGenerator;
import lib_totp.qr.ZxingPngQrGenerator;
import lib_totp.secret.DefaultSecretGenerator;
import lib_totp.secret.SecretGenerator;
import lib_totp.time.SystemTimeProvider;
import lib_totp.time.TimeProvider;
import lib_totp.util.Utils;
import org.apache.commons.codec.binary.Base32;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONTokener;

/**
 *
 * @author AnhEmPhanMem
 */
public class frm_main extends javax.swing.JFrame {

    Timer time, timeStamp;
    private Logger logger = Logger.getLogger(frm_main.class.getName());
    private final int TIME_STEP = 30;

    private final int MAX_WIDTH_QRCODE = 200;
    private final int MAX_HEIGHT_QRCODE = 200;

    private final String[] FIELDS_JSON = {"Username", "Password", "Secret Key"};

    private String DEFAULT_PATH_FILE_NAME = System.getProperty("user.dir") + '\\';
    private String FILENAME = "tableData.json";

    private final int DIGIT_TOKEN = 6;

    private int indexUserLogined;

    private boolean isUserLogined = false;

    DefaultTableModel tableModel;

    public frm_main() {
        initComponents();
        this.tableModel = (DefaultTableModel) this.tb_accountpool.getModel();

        this.lb_qrcode.setText("");
        this.lb_tokenStatus.setText("");
        this.txt_directory.setText(DEFAULT_PATH_FILE_NAME + FILENAME);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_title = new javax.swing.JLabel();
        lb_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lb_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        lb_qrcode = new javax.swing.JLabel();
        txt_checktoken = new javax.swing.JTextField();
        lb_checkOTP = new javax.swing.JLabel();
        lb_tokenStatus = new javax.swing.JLabel();
        txt_otpToken = new javax.swing.JTextField();
        btn_copy = new javax.swing.JButton();
        lb_OTPtoken = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_accountpool = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_otpauth = new javax.swing.JTextArea();
        lb_otpauth = new javax.swing.JLabel();
        lb_timer = new javax.swing.JLabel();
        btn_checktoken = new javax.swing.JButton();
        btn_openFile = new javax.swing.JButton();
        btn_saveFile = new javax.swing.JButton();
        btn_setupPathFile = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_directory = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TOTP");
        setMinimumSize(new java.awt.Dimension(580, 600));
        setName("TOTP"); // NOI18N
        setPreferredSize(new java.awt.Dimension(542, 530));
        setResizable(false);
        setSize(new java.awt.Dimension(580, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_title.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lb_title.setText("TOTP");
        lb_title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 8, -1, -1));

        lb_username.setText("Username:");
        getContentPane().add(lb_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 61, -1, -1));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 83, 200, -1));

        lb_password.setText("Password:");
        getContentPane().add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 111, -1, -1));
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 133, 200, -1));

        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 161, -1, -1));

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 161, -1, -1));

        lb_qrcode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_qrcode.setText("QRCode Is HERE!!!");
        lb_qrcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lb_qrcode.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lb_qrcode.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(lb_qrcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));
        getContentPane().add(txt_checktoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 208, 124, -1));

        lb_checkOTP.setText("Check Token TOTP");
        getContentPane().add(lb_checkOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lb_tokenStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_tokenStatus.setText("Token Status");
        lb_tokenStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lb_tokenStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 40, 40));

        txt_otpToken.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        txt_otpToken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_otpToken.setText("######");
        txt_otpToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otpTokenActionPerformed(evt);
            }
        });
        getContentPane().add(txt_otpToken, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 271, 190, 78));

        btn_copy.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btn_copy.setText("Copy");
        btn_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_copyActionPerformed(evt);
            }
        });
        getContentPane().add(btn_copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 60, 20));

        lb_OTPtoken.setText("OTP Token");
        getContentPane().add(lb_OTPtoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        tb_accountpool.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Secret Key", "Token", "Timer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_accountpool);
        if (tb_accountpool.getColumnModel().getColumnCount() > 0) {
            tb_accountpool.getColumnModel().getColumn(0).setMinWidth(50);
            tb_accountpool.getColumnModel().getColumn(0).setPreferredWidth(100);
            tb_accountpool.getColumnModel().getColumn(0).setMaxWidth(200);
            tb_accountpool.getColumnModel().getColumn(1).setMinWidth(100);
            tb_accountpool.getColumnModel().getColumn(1).setPreferredWidth(100);
            tb_accountpool.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 520, 120));

        txt_otpauth.setColumns(20);
        txt_otpauth.setLineWrap(true);
        txt_otpauth.setRows(5);
        jScrollPane2.setViewportView(txt_otpauth);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 271, 300, 78));

        lb_otpauth.setText("OTPAuth");
        getContentPane().add(lb_otpauth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lb_timer.setText("Timer");
        getContentPane().add(lb_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        btn_checktoken.setText("Check");
        btn_checktoken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checktokenActionPerformed(evt);
            }
        });
        getContentPane().add(btn_checktoken, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 208, -1, -1));

        btn_openFile.setText("Open");
        btn_openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_openFileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_openFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, -1));

        btn_saveFile.setText("Save");
        btn_saveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveFileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_saveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));

        btn_setupPathFile.setText("Edit");
        btn_setupPathFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setupPathFileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_setupPathFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        txt_directory.setEditable(false);
        txt_directory.setColumns(20);
        txt_directory.setLineWrap(true);
        txt_directory.setRows(5);
        txt_directory.setMaximumSize(new java.awt.Dimension(200, 30));
        txt_directory.setMinimumSize(new java.awt.Dimension(100, 20));
        jScrollPane3.setViewportView(txt_directory);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 260, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    int row = 0, col = 0;
//    private final int MAX_ROW = 10;
//    private final int MAX_COLUMN = 3;
    ImageIcon imageValidStatus = new ImageIcon(new ImageIcon("src/assets/icons/valid.png").getImage().getScaledInstance(32, 32, Image.SCALE_DEFAULT));
    ImageIcon imageInvalidStatus = new ImageIcon(new ImageIcon("src/assets/icons/invalid.png").getImage().getScaledInstance(32, 32, Image.SCALE_DEFAULT));

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed

        String username = txt_username.getText();
        String password = new String(txt_password.getPassword());

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (this.isExistedUsernameInTable(username)) {
            JOptionPane.showMessageDialog(this, "Username is existed in table.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password cannot be empty.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Mặc định là đăng ký xong là phải login.
        this.isUserLogined = false;

        this.lb_qrcode.setIcon(null);
        this.txt_otpToken.setText("######");
        this.lb_timer.setText("...s");
        this.txt_otpauth.setText("");

        SecretGenerator secretGenerator = new DefaultSecretGenerator();

        Object[] rowData = new Object[this.tableModel.getColumnCount()];
        int col = 0;
        rowData[col++] = username;
        rowData[col++] = password;
        String secret = secretGenerator.generate();
        rowData[col++] = secret;

        rowData[col++] = this.getToken(secret);
        this.startTime(null, false);

        this.tableModel.addRow(rowData);

        JOptionPane.showMessageDialog(this, "Register successfully!",
                "Success", JOptionPane.NO_OPTION);

        this.lb_tokenStatus.setIcon(null);

    }//GEN-LAST:event_btn_registerActionPerformed

    private void txt_otpTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otpTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otpTokenActionPerformed

//    private String updatetimestamp() {
//        return String.valueOf(System.currentTimeMillis() / 1000L);
//    }
//
//    private String getTime() {
//        long k = 30 - (System.currentTimeMillis() / 1000L % 30);
//        return String.valueOf(k);
//    }

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed

        if (this.txt_username.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username cannot be empty.",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        for (int i = 0; i < this.tableModel.getRowCount(); i++) {
            String username = this.tableModel.getValueAt(i, FieldTable.USERNAME).toString();
            String password = this.tableModel.getValueAt(i, FieldTable.PASSWORD).toString();
            if (username.equals(this.txt_username.getText()) && password.equals(new String(this.txt_password.getPassword()))) {
                this.isUserLogined = true;
                this.indexUserLogined = i;
                this.btn_copy.setEnabled(true);
                this.generateQR();
                this.txt_otpToken.setText(this.getToken(this.tableModel.getValueAt(indexUserLogined, FieldTable.SECRET_KEY).toString()));
                this.startTime(null, true);
                JOptionPane.showMessageDialog(this, "Logined success.",
                        "Success", JOptionPane.DEFAULT_OPTION);
                return;
            }
        }

        this.lb_tokenStatus.setIcon(null);

        JOptionPane.showMessageDialog(this, "Username and Passowrd is not correct.",
                "Error", JOptionPane.ERROR_MESSAGE);


    }//GEN-LAST:event_btn_loginActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_copyActionPerformed

        StringSelection stringSelection = new StringSelection(this.txt_otpToken.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }//GEN-LAST:event_btn_copyActionPerformed

    private void btn_checktokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checktokenActionPerformed
        // TODO add your handling code here:

        if (!this.isUserLogined) {
            JOptionPane.showMessageDialog(this, "You must be login before check token!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        TimeProvider timeProvider = new SystemTimeProvider();

        // get n-digits code.
        CodeGenerator codeGenerator = new DefaultCodeGenerator();
        CodeVerifier codeVerifier = new DefaultCodeVerifier(codeGenerator, timeProvider);

        // secret = the shared secret for the user
        // code = the code submitted by the user
        boolean successful = codeVerifier.isValidCode(this.tableModel.getValueAt(indexUserLogined, FieldTable.SECRET_KEY).toString(), this.txt_checktoken.getText());

        if (successful) {
            this.lb_tokenStatus.setIcon(this.imageValidStatus);
        } else {
            this.lb_tokenStatus.setIcon(this.imageInvalidStatus);
        }
    }//GEN-LAST:event_btn_checktokenActionPerformed

    private void btn_openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_openFileActionPerformed
//        // TODO add your handling code here:

        try (FileReader reader = new FileReader(this.txt_directory.getText())) {
            // Parse JSON từ file
            JSONTokener tokener = new JSONTokener(reader);
            JSONArray jsonArray = new JSONArray(tokener);

            if (jsonArray.length() == 0) {
                JOptionPane.showMessageDialog(this, "No data to import!",
                        "Error", JOptionPane.OK_OPTION);
                return;
            }

            // Lấy model hiện tại của JTable
//            String[] columnNames = this.tableModel.get;
            // Duyệt qua từng hàng (JSONObject) trong JSONArray
            int indexSameUsername = 0;

            for (int i = 0; i < jsonArray.length(); i++) {
                JSONObject rowObject = jsonArray.getJSONObject(i);
                Object[] rowData = new Object[this.tableModel.getColumnCount()];

                // Nếu dữ liệu từ file giống trùng username thì bỏ qua
                if (this.isExistedUsernameInTable((String) rowObject.get(FIELDS_JSON[FieldTable.USERNAME]))) {
                    indexSameUsername++;
                    continue;
                }

                // Lấy từng giá trị của mỗi cột theo tên cột
                for (int col = 0; col < FIELDS_JSON.length; col++) {
                    rowData[col] = rowObject.get(FIELDS_JSON[col]);
                }

                rowData[FieldTable.TOKEN] = this.getToken((String) rowData[FieldTable.SECRET_KEY]);
                this.startTime(null, false);
                // Thêm hàng vào model
                this.tableModel.addRow(rowData);

            }

            if (indexSameUsername == jsonArray.length()) {
                JOptionPane.showMessageDialog(this, "You have been imported!",
                        "Success", JOptionPane.OK_OPTION);
            }

            // Thiết lập model mới cho JTable
//            this.tb_accountpool.set(tableModel);
//            this.updateTableWithNewData(this.tb_accountpool, tableModel);
        } catch (IOException e) {
            e.printStackTrace();
        }

//        // TODO add your handling code here:
//        try {
//            BufferedReader br = null;
////            String workingDir = System.getProperty("user.dir");
////            String filename = workingDir + DEFAULT_PATH_FILE_NAME ;
//            String filename = DEFAULT_PATH_FILE_NAME;
//            br = new BufferedReader(new FileReader(filename));
//            StringBuffer sb = new StringBuffer();
//            JOptionPane.showMessageDialog(null, "Da mo file thanh cong");
////            char[] ca = new char[5];
////            while(br.ready()){
////                int len = br.read(ca);
////                sb.append(ca, 0, len);
////            }
//            br.close();
//            System.out.println("Du lieu la " + "" + br);
////            String chuoi = sb.toString();
////            txt_banma.setText(chuoi);
//        } catch (IOException e) {
//            Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, e);
//        }
    }//GEN-LAST:event_btn_openFileActionPerformed

    private void btn_setupPathFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setupPathFileActionPerformed
        // TODO add your handling code here:
        String path = JOptionPane.showInputDialog(this,
                "Your path?", this.txt_directory.getText());
        this.txt_directory.setText(path);
    }//GEN-LAST:event_btn_setupPathFileActionPerformed

    private void btn_saveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveFileActionPerformed
        // TODO add your handling code here:
//        try {
//            BufferedWriter bw = null;
//            String filename = DEFAULT_PATH_FILE_NAME;
////            String banMa = txt_banma.getText();
//            bw = new BufferedWriter(new FileWriter(filename));
////            bw.write(banMa);
//            bw.close();
//            JOptionPane.showMessageDialog(null, "Da luu file thanh cong");
//        } catch (IOException e) {
//            Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, e);
//        }

        if (this.tableModel.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No data to save!",
                    "Info", JOptionPane.OK_OPTION);
            return;
        }

        JSONArray jsonArray = new JSONArray();
//        TableModel model = this.tableModel;

        // Duyệt qua các hàng và cột trong JTable
        for (int row = 0; row < this.tableModel.getRowCount(); row++) {
            JSONObject rowObject = new JSONObject();
            for (int col = 0; col <= FieldTable.SECRET_KEY; col++) { // model.getColumnCount()
                String columnName = this.tableModel.getColumnName(col);
                Object cellValue = this.tableModel.getValueAt(row, col);
                rowObject.put(columnName, cellValue);  // Gán giá trị cho từng cột
            }
            jsonArray.put(rowObject);  // Thêm hàng vào mảng JSON
        }

        // Ghi JSON ra file
        try (FileWriter file = new FileWriter(this.txt_directory.getText())) {
            file.write(jsonArray.toString(4));  // Ghi dữ liệu với indent = 4. // Định dạng đẹp với thụt đầu dòng 4 khoảng trắng
            file.flush();
            JOptionPane.showMessageDialog(this, "Data saved successfully!",
                    "Success", JOptionPane.OK_OPTION);
        } catch (IOException e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_saveFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_main().setVisible(true);
            }
        });
    }

    public void updateTableWithNewData(JTable table, DefaultTableModel newTableModel) {
        // Lấy model hiện tại của bảng
        DefaultTableModel currentTableModel = (DefaultTableModel) table.getModel();

        // Xóa tất cả hàng hiện tại
        currentTableModel.setRowCount(0);

        // Duyệt qua các hàng trong model mới
        for (int i = 0; i < newTableModel.getRowCount(); i++) {
            // Tạo mảng Object để chứa dữ liệu hàng mới
            Object[] rowData = new Object[newTableModel.getColumnCount()];

            // Lấy dữ liệu từ từng hàng trong model mới
            for (int j = 0; j < newTableModel.getColumnCount(); j++) {
                rowData[j] = newTableModel.getValueAt(i, j);
            }

            // Thêm hàng mới vào model hiện tại
            currentTableModel.addRow(rowData);
        }
    }

    private void reset_form() {
        final String EMPTY = "";
        this.txt_password.setText(EMPTY);
        this.txt_username.setText(EMPTY);
        this.lb_otpauth.setText(EMPTY);
        this.lb_tokenStatus.setIcon(null);
        this.lb_qrcode.setIcon(null);
        this.txt_otpToken.setText("######");
        this.lb_timer.setText(EMPTY);
    }

    long currentTime = TIME_STEP - (new SystemTimeProvider().getTime() % TIME_STEP);

    private void startTime(java.awt.event.ActionEvent evt, boolean isDisplayTime) {
        TimeProvider timeProvider = new SystemTimeProvider();

        // Hiện thời gian hay không?
        if (isDisplayTime && this.isUserLogined) {
            this.lb_timer.setText(String.valueOf(TIME_STEP - (timeProvider.getTime() % TIME_STEP)) + "s");
        }
        time = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String digits = "";
                TimeProvider timeProvider1 = new SystemTimeProvider();
                try {
                    currentTime = TIME_STEP - (timeProvider1.getTime() % TIME_STEP);
                    digits = getDigitsFromHash(generateHash(tb_accountpool.getValueAt(indexUserLogined, 2).toString(), timeProvider1.getTime() / TIME_STEP));
                    // Hiện thời gian hay không?
                    if (isDisplayTime && isUserLogined) {
                        lb_timer.setText(String.valueOf(currentTime) + "s");
                        txt_otpToken.setText(digits);
                    } else {
                    }
                    updateTimerInTable();
                    updateTokenInTable();
                } catch (InvalidKeyException ex) {
                    Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        time.start();
    }

    /**
     * Generate a HMAC-SHA1 hash of the counter number.
     */
    private byte[] generateHash(String key, long counter) throws InvalidKeyException, NoSuchAlgorithmException {
        byte[] data = new byte[8];
        long value = counter;
        for (int i = 8; i-- > 0; value >>>= 8) {
            data[i] = (byte) value;
        }
        // Create a HMAC-SHA1 signing key from the shared key
        Base32 codec = new Base32();
        byte[] decodedKey = codec.decode(key);
        SecretKeySpec signKey = new SecretKeySpec(decodedKey, HashingAlgorithm.SHA1.getHmacAlgorithm());
        Mac mac = Mac.getInstance(HashingAlgorithm.SHA1.getHmacAlgorithm());
        mac.init(signKey);
        // Create a hash of the counter value
        return mac.doFinal(data);
    }

    /**
     * Get the n-digit code for a given hash.
     */
    private String getDigitsFromHash(byte[] hash) {
        int offset = hash[hash.length - 1] & 0xF;
        long truncatedHash = 0;
        for (int i = 0; i < 4; ++i) {
            truncatedHash <<= 8;
            truncatedHash |= (hash[offset + i] & 0xFF);
        }
        truncatedHash &= 0x7FFFFFFF;
        truncatedHash %= Math.pow(10, DIGIT_TOKEN);
        // Left pad with 0s for a n-digit code
        return String.format("%0" + DIGIT_TOKEN + "d", truncatedHash);
    }

    private String getToken(String secretKey) {
        String digits = "";
        try {
            TimeProvider timeProvider = new SystemTimeProvider();
            digits = this.getDigitsFromHash(this.generateHash(secretKey, timeProvider.getTime() / TIME_STEP));
        } catch (InvalidKeyException ex) {
            Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
        }
        return digits;
    }

    private void generateQR() {
        QrData data = new QrData.Builder()
                .label(new String(this.txt_password.getPassword()))
                .secret(this.tableModel.getValueAt(indexUserLogined, 2).toString())
                .issuer(this.txt_username.getText())
                .algorithm(HashingAlgorithm.SHA1) // More on this below
                .digits(DIGIT_TOKEN)
                .period(TIME_STEP)
                .build();

        this.txt_otpauth.setText(data.getUri());

        QrGenerator generator = new ZxingPngQrGenerator();
        try {
            byte[] imageData = generator.generate(data);
            String mimeType = generator.getImageMimeType();
            String dataUri = Utils.getDataUriForImage(imageData, mimeType);

            // Remove the prefix if the base64 string has "data:image/png;base64," or similar
            String base64Image = dataUri.split(",")[1];
            // Decode base64 string into byte array
            byte[] imageBytes = Base64.getDecoder().decode(base64Image);

            // Convert byte array into BufferedImage
            ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes);
            BufferedImage image;
            try {
                image = ImageIO.read(bis);
                // Scale the image if necessary
                Image scaledImage = image.getScaledInstance(MAX_WIDTH_QRCODE, MAX_HEIGHT_QRCODE, Image.SCALE_DEFAULT);

                // Create ImageIcon and set it to JLabel
                ImageIcon imageIcon = new ImageIcon(scaledImage);

                this.lb_qrcode.setIcon(imageIcon);

            } catch (IOException ex) {
                Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (QrGenerationException ex) {
            Logger.getLogger(frm_main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //update timer in table

    private void updateTimerInTable() {
        TimeProvider timeProvider = new SystemTimeProvider();
        for (int i = 0; i < this.tableModel.getRowCount(); i++) {
            long currentTime = TIME_STEP - (timeProvider.getTime() % TIME_STEP);
            this.tableModel.setValueAt(String.valueOf(currentTime) + "s", i, 4);
        }
    }
//update token in table

    private void updateTokenInTable() {

        for (int i = 0; i < this.tableModel.getRowCount(); i++) {
            this.tableModel.setValueAt(this.getToken(this.tableModel.getValueAt(i, 2).toString()), i, 3);
        }
    }

    private boolean isExistedUsernameInTable(String username) {

        for (int i = 0; i < this.tableModel.getRowCount(); i++) {
            if (username.equals(this.tableModel.getValueAt(i, 0))) {
                return true;
            }
        }

        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_checktoken;
    private javax.swing.JButton btn_copy;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_openFile;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_saveFile;
    private javax.swing.JButton btn_setupPathFile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_OTPtoken;
    private javax.swing.JLabel lb_checkOTP;
    private javax.swing.JLabel lb_otpauth;
    private javax.swing.JLabel lb_password;
    private javax.swing.JLabel lb_qrcode;
    private javax.swing.JLabel lb_timer;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_tokenStatus;
    private javax.swing.JLabel lb_username;
    private javax.swing.JTable tb_accountpool;
    private javax.swing.JTextField txt_checktoken;
    private javax.swing.JTextArea txt_directory;
    private javax.swing.JTextField txt_otpToken;
    private javax.swing.JTextArea txt_otpauth;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
