
import dev.samstevens.totp.code.CodeGenerator;
import dev.samstevens.totp.code.CodeVerifier;
import dev.samstevens.totp.code.DefaultCodeGenerator;
import dev.samstevens.totp.code.DefaultCodeVerifier;
import dev.samstevens.totp.code.HashingAlgorithm;
import dev.samstevens.totp.exceptions.QrGenerationException;
import dev.samstevens.totp.qr.QrDataFactory;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.InputMethodEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Base64;

import dev.samstevens.totp.secret.DefaultSecretGenerator;
import dev.samstevens.totp.secret.SecretGenerator;
import dev.samstevens.totp.qr.QrData;
import dev.samstevens.totp.qr.QrGenerator;
import dev.samstevens.totp.qr.ZxingPngQrGenerator;
import dev.samstevens.totp.time.SystemTimeProvider;
import dev.samstevens.totp.time.TimeProvider;
import static dev.samstevens.totp.util.Utils.getDataUriForImage;
import java.io.ByteArrayInputStream;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author test
 */
public class frm_authenticator extends javax.swing.JFrame {
    
    private Logger logger = Logger.getLogger(frm_authenticator.class.getName());

//    private String ENDPOINT = "https://www.token2.com/tools/qrencode.php?otpauth://totp/TOKEN2:user@token2.com?secret=phanngtestoccuong&issuer=Token2";
//    String ASSETS = "2FA/resources/testDataIcons/filling.png";
//    ImageIcon imageIcon1 = new ImageIcon("test.png"); //100, 100 add your own size
//    ImageIcon imageIcon2 = new ImageIcon("thank.jpg"); //100, 100 add your own size
//    Image image = Toolkit.getDefaultToolkit().getImage("test.png");
    /**
     * Creates new form frm_authenticatore
     */
    public frm_authenticator() {
        initComponents();

//        try {
//            getContentPane().add(new JPanelWithBackground("test.png"));
//        } catch (IOException e) {
//                        this.logger.log(Level.SEVERE, e.getMessage());
//            throw new RuntimeException(e);
//        }
        setSize(900, 640);
        
        this.lb_qrcode.setText("");
        this.txt_messageStatus.setText("");

        // code Harryitc
//        try {
////            label1.setIcon(imageIcon1);
////            this.lb_qrcode.setText("");
//            this.lb_qrcode.setIcon(imageIcon1);
//        } catch (Exception e) {
//            this.logger.log(Level.SEVERE, e.getMessage());
//        }
//        this.txt_secret.lis((observable, oldValue, newValue) -> {
//            System.out.println("textfield changed from " + oldValue + " to " + newValue);
//        });
//        this.txt_secret.addKeyListener(event -> {
//            this.
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pn_image = new javax.swing.JPanel();
        lb_qrcode = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_validate = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_account = new javax.swing.JTextField();
        txt_secret = new javax.swing.JTextField();
        txt_token = new javax.swing.JTextField();
        btn_check = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_messageStatus = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_oauth = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Demo TOTP");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Account name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Token");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("QRCode");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        jButton2.setText("Clean");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 110, 30));

        jButton4.setText("Generate");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 90, 30));

        pn_image.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lb_qrcode.setText("jLabel12");

        javax.swing.GroupLayout pn_imageLayout = new javax.swing.GroupLayout(pn_image);
        pn_image.setLayout(pn_imageLayout);
        pn_imageLayout.setHorizontalGroup(
            pn_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_imageLayout.createSequentialGroup()
                .addComponent(lb_qrcode)
                .addGap(0, 255, Short.MAX_VALUE))
        );
        pn_imageLayout.setVerticalGroup(
            pn_imageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_imageLayout.createSequentialGroup()
                .addComponent(lb_qrcode)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        getContentPane().add(pn_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 300, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Secret key");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txt_validate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_validateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_validate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 130, 30));
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 200, 30));
        getContentPane().add(txt_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, 30));

        txt_secret.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_secret.setEnabled(false);
        txt_secret.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txt_secretHierarchyChanged(evt);
            }
        });
        txt_secret.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_secretInputMethodTextChanged(evt);
            }
        });
        txt_secret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_secretActionPerformed(evt);
            }
        });
        txt_secret.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                textChangedHandler(evt);
            }
        });
        txt_secret.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_secretKeyPressed(evt);
            }
        });
        getContentPane().add(txt_secret, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 300, 30));

        txt_token.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txt_token.setText("******");
        txt_token.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_token.setDoubleBuffered(true);
        txt_token.setEnabled(false);
        getContentPane().add(txt_token, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 150, 90));

        btn_check.setText("Check");
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 90, 30));

        jButton6.setText("Clear");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 60, 30));

        jButton7.setText("Clear");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 60, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("OTPAuth");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Check Validation");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        txt_messageStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_messageStatus.setText("valid");
        getContentPane().add(txt_messageStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        jLabel15.setText("*Note: reset everything in screen.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Status:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        txt_oauth.setEditable(false);
        txt_oauth.setColumns(20);
        txt_oauth.setLineWrap(true);
        txt_oauth.setRows(5);
        txt_oauth.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_oauth);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 400, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SecretGenerator secretGenerator = new DefaultSecretGenerator();
        String secret = secretGenerator.generate();
        this.txt_secret.setText(secret);
        
        QrData data = new QrData.Builder()
                .label(this.txt_account.getText())
                .secret(secret)
                .issuer(this.txt_username.getText())
                .algorithm(HashingAlgorithm.SHA1) // More on this below
                .digits(6)
                .period(30)
                .build();
        
        this.txt_oauth.setText(data.getUri());
        
        QrGenerator generator = new ZxingPngQrGenerator();
        try {
            byte[] imageData = generator.generate(data);
            String mimeType = generator.getImageMimeType();
            String dataUri = getDataUriForImage(imageData, mimeType);
            System.out.println("frm_authenticator.jButton4ActionPerformed()" + dataUri);

            // Remove the prefix if the base64 string has "data:image/png;base64," or similar
            String base64Image = dataUri.split(",")[1];
            // Decode base64 string into byte array
            byte[] imageBytes = Base64.getDecoder().decode(base64Image);

            // Convert byte array into BufferedImage
            ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes);
            BufferedImage image;
            try {
                image = ImageIO.read(bis);
                // Scale the image if necessary
                Image scaledImage = image.getScaledInstance(300, 300, Image.SCALE_DEFAULT);

                // Create ImageIcon and set it to JLabel
                ImageIcon imageIcon = new ImageIcon(scaledImage);

//                ImageIcon imageIcon = new ImageIcon(new ImageIcon(dataUri).getImage().getScaledInstance(300, 300, Image.SCALE_DEFAULT)); //100, 100 add your own size
                this.lb_qrcode.setIcon(imageIcon);
                
            } catch (IOException ex) {
                Logger.getLogger(frm_authenticator.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (QrGenerationException ex) {
            Logger.getLogger(frm_authenticator.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void textChangedHandler(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textChangedHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_textChangedHandler

    private void txt_secretInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_secretInputMethodTextChanged
        // TODO add your handling code here:
        System.out.println("new value = " + this.txt_secret.getText());
        System.out.println("event = " + evt.getText());
    }//GEN-LAST:event_txt_secretInputMethodTextChanged

    private void txt_secretKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_secretKeyPressed

    }//GEN-LAST:event_txt_secretKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        final String EMPTY = "";
        this.txt_account.setText(EMPTY);
        this.txt_secret.setText(EMPTY);
        this.txt_username.setText(EMPTY);
        this.txt_validate.setText(EMPTY);
        this.txt_messageStatus.setText(EMPTY);
        this.lb_qrcode.setIcon(null);
        this.txt_token.setText("******");
        this.txt_validate.setText(EMPTY);
        this.txt_oauth.setText(EMPTY);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_validateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_validateActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_validateActionPerformed

    private void txt_secretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_secretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_secretActionPerformed

    private void txt_secretHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txt_secretHierarchyChanged
        // TODO add your handling code here:
        System.out.println("frm_authenticator.txt_secretHierarchyChanged()");
    }//GEN-LAST:event_txt_secretHierarchyChanged

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        System.out.println("frm_authenticator.jButton4MouseClicked() = " + this.txt_secret.getText());
        this.txt_secretKeyPressed(null);
    }//GEN-LAST:event_jButton4MouseClicked

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        // TODO add your handling code here:

        TimeProvider timeProvider = new SystemTimeProvider();
        CodeGenerator codeGenerator = new DefaultCodeGenerator();
        CodeVerifier verifier = new DefaultCodeVerifier(codeGenerator, timeProvider);

        // secret = the shared secret for the user
        // code = the code submitted by the user
        boolean successful = verifier.isValidCode(this.txt_secret.getText(), this.txt_validate.getText());
        
        this.txt_messageStatus.setText(successful ? "VALID" : "INVALID");
    }//GEN-LAST:event_btn_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_authenticator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_authenticator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_authenticator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_authenticator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_authenticator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_check;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_qrcode;
    private javax.swing.JPanel pn_image;
    private javax.swing.JTextField txt_account;
    private javax.swing.JLabel txt_messageStatus;
    private javax.swing.JTextArea txt_oauth;
    private javax.swing.JTextField txt_secret;
    private javax.swing.JTextField txt_token;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_validate;
    // End of variables declaration//GEN-END:variables
}
